# Generated by Django 5.0.3 on 2024-06-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
